# Generated by Django 5.2.6 on 2025-09-25 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_variation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('activewear', 'Activewear'), ('formal', 'Formal Wear'), ('casual', 'Casual Wear'), ('other', 'Other')], default='other', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('source', models.CharField(choices=[('store_purchase', 'Purchased from Store'), ('manual_upload', 'Manually Added'), ('gift', 'Gift'), ('other', 'Other')], default='manual_upload', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags like 'casual, work, party'", max_length=500, null=True)),
                ('times_worn', models.PositiveIntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_product', models.ForeignKey(blank=True, help_text='Link to store product if purchased from our store', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('times_worn', models.PositiveIntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('outfit_image', models.ImageField(blank=True, null=True, upload_to='outfits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='outfits', to='wardrobe.wardrobeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_outfits', models.PositiveIntegerField(default=0)),
                ('most_worn_category', models.CharField(blank=True, max_length=20, null=True)),
                ('favorite_season', models.CharField(blank=True, max_length=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
