# Generated by Django 5.2.6 on 2025-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250828_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='face_image',
            field=models.ImageField(blank=True, help_text='Close-up face image for virtual try-on', null=True, upload_to='user_images/face/'),
        ),
        migrations.AddField(
            model_name='account',
            name='full_body_image',
            field=models.ImageField(blank=True, help_text='Full body image for pants/shoes try-on', null=True, upload_to='user_images/full_body/'),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='upper_body_image',
            field=models.ImageField(blank=True, help_text='Upper body image for shirts/tops try-on', null=True, upload_to='user_images/upper_body/'),
        ),
    ]
