# Generated by Django 5.2.6 on 2025-10-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_variation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='New York', max_length=100)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherOutfitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy'), ('foggy', 'Foggy')], max_length=20)),
                ('temperature_range', models.CharField(choices=[('very_cold', 'Very Cold (< 0°C)'), ('cold', 'Cold (0-10°C)'), ('cool', 'Cool (10-20°C)'), ('mild', 'Mild (20-25°C)'), ('warm', 'Warm (25-30°C)'), ('hot', 'Hot (> 30°C)')], max_length=20)),
                ('recommended_categories', models.CharField(max_length=200)),
                ('recommended_colors', models.CharField(blank=True, max_length=200)),
                ('recommended_fabrics', models.CharField(blank=True, max_length=200)),
                ('style_advice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DressRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('style_tips', models.TextField(blank=True)),
                ('color_suggestions', models.CharField(blank=True, max_length=200)),
                ('fabric_suggestions', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_products', models.ManyToManyField(blank=True, to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress_recommender.weatherdata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
